language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy2.7"
    - "pypy3.5"
install:
    - pip install pytest
    - python setup.py install
script:
  - py.test -m 'not wip' -v
